[SERVICE]
    Flush        5
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5

[OUTPUT]
    Name            tcp
    Match           *
    Host            10.10.10.44
    Port            5044
    Format          json_lines
