input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  json {
    source => "log"
    target => "docker"
  }
  mutate {
    remove_field => ["log"]
  }
}

output {
  opensearch {
    hosts => ["http://10.10.10.45:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
